### PR TITLE
Upgrade to Laravel 5.7

### PR DESCRIPTION
**Pull request by AdrianHL**
Update dependencies to match Laravel 5.7 requirements

### CODE REVIEW

**Comment by serverfire** [comment]
It needs more work to support laravel 5.7

**Comment by AdrianHL** [comment]
Could you shed more light into what changes are needed? I may help to add this support :)

**Comment by serverfire** [comment]
We had a pull request with many changes for laravel 5.7 but had few issues, 

Have you tested this pull request changes with laravel 5.7? did all the functions work?

**Comment by AdrianHL** [comment]
Going to check it now.

**Comment by AdrianHL** [comment]
I can't say 100% that it's working but haven't found any issues so far.

**Comment by serverfire** [comment]
Thank you will release it as alpha version so we can keep testing it, Please use it and let us know if you see any issue

**Pull request merged**
