### PR TITLE
Add a prefix to database tables to not conflict with existing in app …

### PR DESCRIPTION
**Pull request by mattwadey**
…tables

### CODE REVIEW

**Comment by serverfire** [comment]
Thank you for contribute .

which table have conflict ?

I think adding prefix would confuse developers !

Check default table of laravel , they don't have prefix

**Comment by mattwadey** [comment]
Hi, 

Yeah the “links” table is one I already had so it throws an error. As it’s a pretty generic name for a table it could easily happen for someone else.

We could make the prefix dynamic with a default of an empty string and then change the readme to say “To avoid conflicts you may want to install this with a db prefix just set one in the config before installing”?

Then define a name for that config var? So for example we might have:

## in main app/config.php (After instruction through readme)
// Main site server path
    ’serverfire' => [
        ‘prefix' => ’sf_’,
    ],

## in models/Link.php
class Link extends Model {
    protected $table = 'links’;

    __construct(){
	$this->table = \Config::get(‘serverfire.prefix’).$this->table;
    }
}

Thanks,


e: mattwade@darwincreative.co.uk <mailto:matt@mnwade.co.uk>                  t: 0191 640 2266
w: www.darwincreative.co.uk <http://www.mnwade.co.uk/> 				  m: 07595 303 514

Adamson House :: 65 Westgate Road :: Newcastle :: NE1 1SG

This e-mail is confidential and may be privileged. It may be read, copied and used only by the intended recipient. No communication sent by email to or from Darwin Creative is intended to give rise to contractual or other legal liability, Apart from liability which cannot be excluded under English law

**Comment by serverfire** [comment]
@mattwadey 

That is great idea , if you could change your code and send it again , so i can test it and merge it .

for default let prefix be empty and we could change links model to panel_links to not be general 

Thank you

**Comment by serverfire** [comment]
@mattwadey any news on this ?

**Pull request closed without merging**
