### PR TITLE
model path

### PR DESCRIPTION
**Pull request by wtom**
hi,
i wanted to put my Models in the App/Models/ directory, so i added a modelPath variable in the config and wrote a getModel method in the AppHelper, that is now used instead of writing the same code over and over.

### CODE REVIEW

**Comment by pardo-bsso** [comment]
Hello @serverfire , we are needing something like this too in order to have a cleaner codebase, what is needed to have this merged besides documentation ? 

Thanks!

**Comment by serverfire** [comment]
@wtom thank you for pull request .

@pardo-bsso this pull request have few problem .

1. it is not clean , it say want to fix model Path but it change order of links in menu too 
2. use clone of rapyd-laravel

**Comment by terion-name** [comment]
Absolutely needed

**Comment by wtom** [comment]
i can start a pull request, just with the model path code, if you don't want the sort order

**Pull request closed without merging**
