### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by RezaAb**
change vendor:publish tag names
change MainController for calling another route with current URI

### CODE REVIEW

**Comment by serverfire** [comment]
Hi Reza. Thanks.
why you change the tag names?

**Comment by RezaAb** [comment]
> Hi Reza. Thanks.
> why you change the tag names?

Hi. when the installation command wants to call vendor:publish, it publish all package with that tag name that you have in composer.json. so I renamed these tag names.

**Comment by serverfire** [comment]
> 
> 
> > Hi Reza. Thanks.
> > why you change the tag names?
> 
> Hi. when the installation command wants to call vendor:publish, it publish all package with that tag name that you have in composer.json. so I renamed these tag names.

good. and what about MainController? Is it necessary?

**Comment by RezaAb** [comment]
> > > Hi Reza. Thanks.
> > > why you change the tag names?
> > 
> > 
> > Hi. when the installation command wants to call vendor:publish, it publish all package with that tag name that you have in composer.json. so I renamed these tag names.
> 
> good. and what about MainController? Is it necessary?

yeah. when we have a duplicate route that has different functionality, That is the preferred route.

**Pull request merged**
