### PR TITLE
Hide links in Menu

### PR DESCRIPTION
**Pull request by acekyd**
This feature allows users choose which links should appear on the dashboard menu. And can easily hide any they want

### CODE REVIEW

**Comment by serverfire** [comment]
@acekyd thank you for great work , we will review it ,

**Comment by acekyd** [comment]
Great @serverfire, would be waiting

**Comment by acekyd** [comment]
screen2
screen1

**Comment by serverfire** [comment]
@acekyd sorry for late merege , thank you

**Pull request merged**
