### PR TITLE
Model path config

### PR DESCRIPTION
**Pull request by wtom**
> hi,
> i wanted to put my Models in the App/Models/ directory, so i added a modelPath variable in the config and wrote a getModel method in the AppHelper, that is now used instead of writing the same code over and over.

here just the pull request with the model path config

### CODE REVIEW

**Comment by serverfire** [comment]
I have to check your code , i'm not sure about it

**Comment by coopers98** [comment]
I second this.  Forcing users to put model files in the root /app folder is a major turn off

**Comment by serverfire** [comment]
@coopers98 have you test this pull request? Are you sure it's working?

**Comment by wtom** [comment]
I have this running in productive environment since 6 months. No problems so far.

**Comment by serverfire** [comment]
@wtom thank you for great work , 

@coopers98 it is in master branch , give it a try

**Comment by coopers98** [comment]
Thanks, will pull it in.  I was commenting more about the inability to have Model files other than in /app root, but looking forward to this PR resolving that.

**Pull request merged**
