### PR TITLE
Added french language

### PR DESCRIPTION
**Pull request by bruce-thomas**
I've added a file for french translation.

### CODE REVIEW

**Comment by serverfire** [comment]
@bruce-thomas  Thank you for contribute , keep the good works .

**Comment by bruce-thomas** [comment]
@serverfire thank you for this great tool, which is exactly what I was searching for : a tool to build a clean and customisable admin interface in minutes !

I have noticed that the placeholders in the login form fields (Username and Password) are hard-coded, and thus can not be translated. Should I open an issue for this (and fix it by the way :) ?

**Comment by serverfire** [comment]
@bruce-thomas 
We are very happy when see developers like you love laravelpanel  .

I did fix the place holder in login page . 
Also i  have remove the "Nouveau" from password , it should be just password not "new password" , and use it for placeholder for email 

Thank you

**Comment by bruce-thomas** [comment]
Thanks for the fix !

**Pull request merged**
